package chess;

@Utility
public class TODOS {

    /*

    CURRENT OBJECTIVES:
    TODO: ADD A PIECE MOVING SYSTEM
    TODO: MAKE THE AVAILABLE MOVES COME UP AS CYAN
    TODO: MAKE THE AVAILABLE MOVES CLEAR WHEN YOU CLICK ON A NEW PIECE, AS TO REFRESH THE AVAILABLE MOVES

     */

}
